// File: src/contexts/LanguageContext.jsx
import { createContext, useContext, useState } from "react";

const translations = {
  EN: {
    // Navbar
    home: "Home",
    services: "Services",
    documentation: "Documentation",
    posters: "Posters",
    adminPortal: "Admin Portal",
    // Index Hero
    heroTag: "📋 Modern Tax Solutions for 2025",
    heroTitle1: "Navigate Your Taxes With",
    heroTitle2: "Absolute Clarity.",
    heroDesc: "Expert tax consultation and strategic planning for individuals and enterprises. We help you minimize liabilities and stay fully compliant.",
    getStarted: "Get Started",
    viewServices: "View Services",
    taxSaved: "Tax saved for clients",
    // Stats
    clientsServed: "Clients Served",
    taxSavedLabel: "Tax Saved",
    yearsExperience: "Years Experience",
    clientRating: "Client Rating",
    // Services section
    whatWeDo: "What We Do",
    ourServices: "Our Specialized Services",
    servicesSubtitle: "Comprehensive tax planning and documentation services tailored to your specific financial situation.",
    corporateTax: "Corporate Tax Planning",
    corporateTaxDesc: "Strategic tax minimization, compliance reviews, and financial restructuring for modern enterprises and startups.",
    taxDocumentation: "Tax Documentation",
    taxDocDesc: "Complete preparation, filing, and management of complex tax documentation to ensure audit-readiness year-round.",
    individualConsulting: "Individual Consulting",
    individualDesc: "Personalized wealth management and tax return optimization for high-net-worth individuals and independent contractors.",
    requestService: "Request Service",
    // Testimonials
    testimonials: "Testimonials",
    whatClientsSay: "What Our Clients Say",
    testimonialsSubtitle: "Trusted by thousands of individuals and businesses across the country.",
    // Contact
    getInTouch: "Get In Touch",
    readyOptimize: "Ready to optimize your taxes?",
    contactDesc: "Fill out the form to request a service or send us a message. One of our senior tax consultants will reach out to you within 24 business hours.",
    fastResponse: "Fast Response",
    fastResponseDesc: "We typically reply within 2 hours during business days.",
    secureConfidential: "Secure & Confidential",
    secureDesc: "Your financial data is encrypted and completely private.",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    serviceRequested: "Service Requested",
    selectService: "Select a service...",
    yourMessage: "Your Message (Optional)",
    sendRequest: "Send Request",
    // Posters section
    freeResources: "Free Resources",
    postersResources: "Posters & Resources",
    postersDesc: "Download our free tax deadline posters and preparation checklists for your office wall.",
    downloadPdf: "📥 Download PDF",
    // CTA
    ctaTitle: "Ready to Take Control of Your Taxes?",
    ctaDesc: "Schedule a free 30-minute consultation with our experts and discover how much you could save.",
    bookConsultation: "Book Free Consultation",
    exploreServices: "Explore Services",
    // Services page
    expertTaxServices: "Expert Tax Services",
    servicesPageDesc: "Explore our comprehensive suite of tax consultation and planning services. We leverage decades of expertise to navigate complex tax codes for your benefit.",
    newFeature: "🚀 New Feature",
    smartDiagnostic: "Smart Tax Diagnostic Tool",
    diagnosticDesc: "Not sure which service you need? Use our proprietary AI diagnostic tool. Answer a few simple questions, and our system will match you with the precise tax service and documentation package for your unique situation.",
    runDiagnostic: "Run Free Diagnostic",
    continueBtn: "Continue",
    readyGetStarted: "Ready to get started?",
    readyDesc: "Fill out the form with your details and specific tax requirements. Our specialized team will review your submission and contact you within 24 hours to schedule an initial consultation.",
    directLine: "Direct Line",
    emailSupport: "Email Support",
    fullName: "Full Name",
    selectServiceShort: "Select...",
    additionalInfo: "Additional Information",
    submitRequest: "Submit Request Form",
    secureNote: "Your information is securely encrypted and strictly confidential.",
    requestThisService: "Request This Service",
    // Documentation page
    docTitle: "Documentation & Resources",
    docDesc: "Access our comprehensive library of tax guides, official forms, templates, and policy documents tailored for corporate and individual needs.",
    searchDocs: "Search documents by title, form number, or category...",
    categories: "Categories",
    download: "Download",
    preview: "Preview",
    // Posters page
    postersTitle: "Posters & Infographics",
    postersPageDesc: "Download free printable posters, infographics, and visual guides for your office. Keep your team informed with at-a-glance tax reference materials.",
    // Service Request page
    backToServices: "Back to Services",
    serviceRequest: "Service Request",
    serviceRequestDesc: "Please provide your details below and our advisory team will securely review your case.",
    selectedService: "Selected Service",
    companyName: "Company Name",
    workEmail: "Work Email",
    phoneNumber: "Phone Number",
    optional: "Optional",
    projectDetails: "Project Details & Objectives",
    projectPlaceholder: "Please briefly describe your company's current tax situation, any upcoming deadlines, or specific challenges you are facing...",
    supportingDocs: "Supporting Documents",
    clickUpload: "Click to upload or drag and drop",
    fileTypes: "PDF, DOCX, or Excel files (Max 20MB)",
    submitSecure: "Submit Secure Request",
    encryptedNote: "🔒 256-bit Encrypted & Confidential Submission",
    // Footer
    quickLinks: "Quick Links",
    contact: "Contact",
    newsletter: "Newsletter",
    newsletterDesc: "Subscribe to stay updated on tax regulations and tips.",
    footerDesc: "Expert tax consultation and strategic planning for individuals and enterprises since 2010.",
    footerCopy: "© 2025 TaxPro Advisors. All rights reserved. Strict confidentiality guaranteed.",
    // Admin login
    adminLogin: "Admin Login",
    adminLoginDesc: "Enter your credentials to access the admin portal.",
    username: "Username",
    password: "Password",
    login: "Log In",
    invalidCredentials: "Invalid username or password.",
    backToHome: "Back to Home",
    // Income options
    w2Employment: "W-2 Employment",
    businessOwner: "Business Owner / LLC",
    investmentsCapital: "Investments / Capital Gains",
    incomeQuestion: "What is your primary source of income?",
  },
  SW: {
    home: "Nyumbani",
    services: "Huduma",
    documentation: "Nyaraka",
    posters: "Mabango",
    adminPortal: "Portal ya Msimamizi",
    heroTag: "📋 Suluhisho za Kisasa za Kodi 2025",
    heroTitle1: "Tembea Kodi Zako Kwa",
    heroTitle2: "Uwazi Kamili.",
    heroDesc: "Ushauri wa kitaalamu wa kodi na mipango ya kimkakati kwa watu binafsi na makampuni. Tunakusaidia kupunguza majukumu na kubaki kulingana na sheria.",
    getStarted: "Anza Sasa",
    viewServices: "Tazama Huduma",
    taxSaved: "Kodi iliyookolewa kwa wateja",
    clientsServed: "Wateja Waliohudumwa",
    taxSavedLabel: "Kodi Iliyookolewa",
    yearsExperience: "Miaka ya Uzoefu",
    clientRating: "Ukadiriaji wa Wateja",
    whatWeDo: "Tunachofanya",
    ourServices: "Huduma Zetu Maalum",
    servicesSubtitle: "Mipango kamili ya kodi na huduma za nyaraka zilizobinafsishwa kwa hali yako ya kifedha.",
    corporateTax: "Mipango ya Kodi ya Kampuni",
    corporateTaxDesc: "Upungufu wa kodi wa kimkakati, ukaguzi wa utiifu, na urekebishaji wa kifedha kwa makampuni ya kisasa.",
    taxDocumentation: "Nyaraka za Kodi",
    taxDocDesc: "Maandalizi kamili, uwasilishaji, na usimamizi wa nyaraka ngumu za kodi kuhakikisha utayari wa ukaguzi.",
    individualConsulting: "Ushauri wa Mtu Binafsi",
    individualDesc: "Usimamizi wa mali uliobinafsishwa na uboreshaji wa pato la kodi kwa watu wenye utajiri.",
    requestService: "Omba Huduma",
    testimonials: "Ushuhuda",
    whatClientsSay: "Wateja Wetu Wanasema Nini",
    testimonialsSubtitle: "Tunaaminika na maelfu ya watu binafsi na biashara kote nchini.",
    getInTouch: "Wasiliana Nasi",
    readyOptimize: "Uko tayari kuboresha kodi zako?",
    contactDesc: "Jaza fomu kuomba huduma au kutuma ujumbe. Mmoja wa washauri wetu wakuu wa kodi atawasiliana nawe ndani ya masaa 24.",
    fastResponse: "Majibu ya Haraka",
    fastResponseDesc: "Kawaida tunajibu ndani ya masaa 2 wakati wa siku za kazi.",
    secureConfidential: "Salama na Siri",
    secureDesc: "Data yako ya kifedha imesimbwa na ni ya faragha kabisa.",
    firstName: "Jina la Kwanza",
    lastName: "Jina la Mwisho",
    emailAddress: "Barua Pepe",
    serviceRequested: "Huduma Inayoombwa",
    selectService: "Chagua huduma...",
    yourMessage: "Ujumbe Wako (Hiari)",
    sendRequest: "Tuma Ombi",
    freeResources: "Rasilimali za Bure",
    postersResources: "Mabango na Rasilimali",
    postersDesc: "Pakua mabango yetu ya bure ya tarehe za mwisho za kodi na orodha za maandalizi kwa ofisi yako.",
    downloadPdf: "📥 Pakua PDF",
    ctaTitle: "Uko Tayari Kudhibiti Kodi Zako?",
    ctaDesc: "Panga mashauriano ya bure ya dakika 30 na wataalamu wetu na ugundue kiasi unachoweza kuokoa.",
    bookConsultation: "Panga Mashauriano ya Bure",
    exploreServices: "Gundua Huduma",
    expertTaxServices: "Huduma za Kodi za Kitaalamu",
    servicesPageDesc: "Chunguza seti yetu kamili ya huduma za ushauri na mipango ya kodi.",
    newFeature: "🚀 Kipengele Kipya",
    smartDiagnostic: "Zana ya Uchunguzi wa Kodi",
    diagnosticDesc: "Huna uhakika unahitaji huduma gani? Tumia zana yetu ya uchunguzi wa AI.",
    runDiagnostic: "Endesha Uchunguzi wa Bure",
    continueBtn: "Endelea",
    readyGetStarted: "Uko tayari kuanza?",
    readyDesc: "Jaza fomu na maelezo yako na mahitaji maalum ya kodi.",
    directLine: "Simu ya Moja kwa Moja",
    emailSupport: "Msaada wa Barua Pepe",
    fullName: "Jina Kamili",
    selectServiceShort: "Chagua...",
    additionalInfo: "Maelezo ya Ziada",
    submitRequest: "Wasilisha Fomu ya Ombi",
    secureNote: "Taarifa zako zimesimbwa kwa usalama na ni za siri.",
    requestThisService: "Omba Huduma Hii",
    docTitle: "Nyaraka na Rasilimali",
    docDesc: "Pata maktaba yetu kamili ya miongozo ya kodi, fomu rasmi, templeti, na nyaraka za sera.",
    searchDocs: "Tafuta nyaraka kwa jina, nambari ya fomu, au kategoria...",
    categories: "Kategoria",
    download: "Pakua",
    preview: "Hakiki",
    postersTitle: "Mabango na Infografia",
    postersPageDesc: "Pakua mabango ya bure yanayoweza kuchapishwa, infografia, na miongozo ya kuona kwa ofisi yako.",
    backToServices: "Rudi kwenye Huduma",
    serviceRequest: "Ombi la Huduma",
    serviceRequestDesc: "Tafadhali toa maelezo yako hapa chini na timu yetu ya ushauri itakagua kesi yako kwa usalama.",
    selectedService: "Huduma Iliyochaguliwa",
    companyName: "Jina la Kampuni",
    workEmail: "Barua Pepe ya Kazi",
    phoneNumber: "Nambari ya Simu",
    optional: "Hiari",
    projectDetails: "Maelezo ya Mradi na Malengo",
    projectPlaceholder: "Tafadhali eleza kwa ufupi hali ya sasa ya kodi ya kampuni yako...",
    supportingDocs: "Nyaraka za Msaada",
    clickUpload: "Bofya kupakia au buruta na udondoshe",
    fileTypes: "Faili za PDF, DOCX, au Excel (Maks 20MB)",
    submitSecure: "Wasilisha Ombi Salama",
    encryptedNote: "🔒 Usimbaji wa 256-bit na Wasilisho la Siri",
    quickLinks: "Viungo vya Haraka",
    contact: "Mawasiliano",
    newsletter: "Jarida",
    newsletterDesc: "Jiandikishe kupata habari kuhusu kanuni za kodi na vidokezo.",
    footerDesc: "Ushauri wa kitaalamu wa kodi na mipango ya kimkakati kwa watu binafsi na makampuni tangu 2010.",
    footerCopy: "© 2025 TaxPro Advisors. Haki zote zimehifadhiwa. Usiri mkali unahakikishiwa.",
    adminLogin: "Ingia kwa Msimamizi",
    adminLoginDesc: "Weka kitambulisho chako kufikia portal ya msimamizi.",
    username: "Jina la mtumiaji",
    password: "Neno la siri",
    login: "Ingia",
    invalidCredentials: "Jina la mtumiaji au neno la siri si sahihi.",
    backToHome: "Rudi Nyumbani",
    w2Employment: "Ajira ya W-2",
    businessOwner: "Mmiliki wa Biashara / LLC",
    investmentsCapital: "Uwekezaji / Faida ya Mtaji",
    incomeQuestion: "Chanzo chako kikuu cha mapato ni nini?",
  },
  CHN: {
    home: "首页",
    services: "服务",
    documentation: "文档",
    posters: "海报",
    adminPortal: "管理门户",
    heroTag: "📋 2025年现代税务解决方案",
    heroTitle1: "以",
    heroTitle2: "绝对清晰导航您的税务。",
    heroDesc: "为个人和企业提供专业的税务咨询和战略规划。我们帮助您最小化负债并保持完全合规。",
    getStarted: "开始",
    viewServices: "查看服务",
    taxSaved: "为客户节省的税款",
    clientsServed: "服务客户",
    taxSavedLabel: "节省税款",
    yearsExperience: "年经验",
    clientRating: "客户评分",
    whatWeDo: "我们的工作",
    ourServices: "我们的专业服务",
    servicesSubtitle: "根据您的具体财务状况量身定制的全面税务规划和文件服务。",
    corporateTax: "企业税务规划",
    corporateTaxDesc: "为现代企业和初创公司提供战略税收最小化、合规审查和财务重组。",
    taxDocumentation: "税务文件",
    taxDocDesc: "完成复杂税务文件的准备、提交和管理，确保全年审计准备。",
    individualConsulting: "个人咨询",
    individualDesc: "为高净值个人和独立承包商提供个性化财富管理和税务申报优化。",
    requestService: "请求服务",
    testimonials: "客户评价",
    whatClientsSay: "客户的评价",
    testimonialsSubtitle: "受到全国数千个人和企业的信赖。",
    getInTouch: "联系我们",
    readyOptimize: "准备好优化您的税务了吗？",
    contactDesc: "填写表格请求服务或发送消息。我们的高级税务顾问将在24个工作小时内联系您。",
    fastResponse: "快速响应",
    fastResponseDesc: "我们通常在工作日2小时内回复。",
    secureConfidential: "安全保密",
    secureDesc: "您的财务数据已加密且完全私密。",
    firstName: "名",
    lastName: "姓",
    emailAddress: "电子邮箱",
    serviceRequested: "请求的服务",
    selectService: "选择服务...",
    yourMessage: "您的留言（可选）",
    sendRequest: "发送请求",
    freeResources: "免费资源",
    postersResources: "海报和资源",
    postersDesc: "下载我们免费的税务截止日期海报和办公室准备清单。",
    downloadPdf: "📥 下载PDF",
    ctaTitle: "准备好掌控您的税务了吗？",
    ctaDesc: "安排与我们专家的免费30分钟咨询，了解您可以节省多少。",
    bookConsultation: "预约免费咨询",
    exploreServices: "探索服务",
    expertTaxServices: "专业税务服务",
    servicesPageDesc: "探索我们全面的税务咨询和规划服务套件。",
    newFeature: "🚀 新功能",
    smartDiagnostic: "智能税务诊断工具",
    diagnosticDesc: "不确定需要哪种服务？使用我们的AI诊断工具。",
    runDiagnostic: "运行免费诊断",
    continueBtn: "继续",
    readyGetStarted: "准备好开始了吗？",
    readyDesc: "填写您的详细信息和具体税务要求。",
    directLine: "直线电话",
    emailSupport: "邮件支持",
    fullName: "全名",
    selectServiceShort: "选择...",
    additionalInfo: "附加信息",
    submitRequest: "提交请求表",
    secureNote: "您的信息已安全加密且严格保密。",
    requestThisService: "请求此服务",
    docTitle: "文档和资源",
    docDesc: "访问我们全面的税务指南、官方表格、模板和政策文件库。",
    searchDocs: "按标题、表格编号或类别搜索文件...",
    categories: "类别",
    download: "下载",
    preview: "预览",
    postersTitle: "海报和信息图",
    postersPageDesc: "为您的办公室下载免费的可打印海报、信息图和视觉指南。",
    backToServices: "返回服务",
    serviceRequest: "服务请求",
    serviceRequestDesc: "请在下面提供您的详细信息，我们的顾问团队将安全审查您的案例。",
    selectedService: "已选服务",
    companyName: "公司名称",
    workEmail: "工作邮箱",
    phoneNumber: "电话号码",
    optional: "可选",
    projectDetails: "项目详情和目标",
    projectPlaceholder: "请简要描述贵公司当前的税务状况...",
    supportingDocs: "支持文件",
    clickUpload: "点击上传或拖放",
    fileTypes: "PDF、DOCX或Excel文件（最大20MB）",
    submitSecure: "提交安全请求",
    encryptedNote: "🔒 256位加密和保密提交",
    quickLinks: "快速链接",
    contact: "联系方式",
    newsletter: "通讯",
    newsletterDesc: "订阅以获取税务法规和提示的最新信息。",
    footerDesc: "自2010年以来为个人和企业提供专业税务咨询和战略规划。",
    footerCopy: "© 2025 TaxPro Advisors。保留所有权利。严格保密。",
    adminLogin: "管理员登录",
    adminLoginDesc: "输入您的凭据以访问管理门户。",
    username: "用户名",
    password: "密码",
    login: "登录",
    invalidCredentials: "用户名或密码无效。",
    backToHome: "返回首页",
    w2Employment: "W-2就业",
    businessOwner: "企业主 / LLC",
    investmentsCapital: "投资 / 资本收益",
    incomeQuestion: "您的主要收入来源是什么？",
  },
};

const LanguageContext = createContext({
  lang: "EN",
  setLang: (_l) => {},
  t: (_key) => "",
});

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("EN");
  const t = (key) => translations[lang]?.[key] || translations.EN[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
